### ISSUE TITLE
v1.0.0:  Self render of playermodel

### ISSUE THREAD

**Issue by Haano137** [BunyaPineTree/LethalCompany_ModelReplacementAPI#1]
Not sure if this is an intended feature or not but you while you can see the playermodel (Hatsune Miku example mod) on others, and other on you, you can't see the model on your self. I've tested this using the [3rdPerson mod](https://thunderstore.io/c/lethal-company/p/Verity/3rdPerson/) in multiplayer and this seems to be the case.

**Comment by minatcchi** [comment]
would love to see this be a thing so you can see the arms in game not sure what that would involve though if its a separate player model

**Comment by BunyaPineTree** [comment]
Looking into fixing 3rd person view right now.
Regardless, first person arms in game are handled with an entirely different mesh, and would require the API user to supply that as well. It's not presently high on my to do list, but adding support is on the radar.

**Comment by KalmAndKollected** [comment]
> Looking into fixing 3rd person view right now. Regardless, first person arms in game are handled with an entirely different mesh, and would require the API user to supply that as well. It's not presently high on my to do list, but adding support is on the radar.

Is it possible for the masked enemies to also display the models themselves?

**Comment by BunyaPineTree** [comment]
Yeah, I just haven't had time to dissect the code on masked enemies yet do to the holiday season.

**Comment by BunyaPineTree** [comment]
Closing this because some third person mods are already supported, and I'm currently working on a culling mask fix that will support all of them.
