### ISSUE TITLE
Model glitch when having LethalSnap

### ISSUE THREAD

**Issue by Cracky4589** [BunyaPineTree/LethalCompany_ModelReplacementAPI#101]
Hello, 

When having LethalSnap and ModelReplacementAPI, the default model start glitching. It do not happen with custom models only the default one.

**Comment by Cracky4589** [comment]
I forgot to precise than the model glitch only when using an Emote with LethalEmotesAPI.

**Comment by BunyaPineTree** [comment]
I have a feeling that this is related to a LOD bug that is on the list of things I need to fix, and isn't actually related to LethalSnap.

Once I fix that bug I'll ask and see if the problem you're having is fixed.

**Comment by BunyaPineTree** [comment]
Since this is likely related to the same issue, can you confirm whether the problem still happens? 

https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/issues/92#issuecomment-2118961054

**Comment by Cracky4589** [comment]
I beleive the issu is now fixed. Thanks
