### ISSUE TITLE
Inside facility enemies ignore replaced player

### ISSUE THREAD

**Issue by BoredBean** [BunyaPineTree/LethalCompany_ModelReplacementAPI#106]
I made a mod based on this API.

The models look well, but when my model was replaced, the enemies inside, such as Coil-head and Nutcracker would ignore me.
Outside enemies like giants and old-birds could still see me.
Nutcrackers still gets angry when we collide, but it won't shoot without a target.
When I look up more than about 75 degrees inside facility, the enemies can see me again until they lost my position, at which point they'll go back to being blind.

I'm not sure if this is caused by this API or I did something wrong when making my Mod.

**Comment by BunyaPineTree** [comment]
This likely has to do with colliders on your model getting in the way of ray casts used by enemy AI. If your colliders aren't istrigger, they need to be.

**Comment by BunyaPineTree** [comment]
I've played the game since answering this issue, and haven't had the problem myself. I'll close the issue since it's probably model specific.

**Comment by BoredBean** [comment]
I think isTrigger colliders still block the line of sight.
But shrinking the colliders helps.
Thanks
