### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object OffsetBuilderEditor.OnInspectorGUI () (at ./Library/PackageCache/com.bunya.modelreplacementsdk@91ccd7f277/Editor/ItemOffsetEditor.cs:63) UnityEditor.UIElements.InspectorElement+<>c__DisplayClass72_0.<CreateInspectorElementUsingIMGUI>b__0 () (at <2e279d988b9d4542841de511fbfdf8c2>:0) UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

### ISSUE THREAD

**Issue by NovaTheFurryDev** [BunyaPineTree/LethalCompany_ModelReplacementAPI#108]
NullReferenceException: Object reference not set to an instance of an object
OffsetBuilderEditor.OnInspectorGUI () (at ./Library/PackageCache/com.bunya.modelreplacementsdk@91ccd7f277/Editor/ItemOffsetEditor.cs:63)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass72_0.<CreateInspectorElementUsingIMGUI>b__0 () (at <2e279d988b9d4542841de511fbfdf8c2>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

![image](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/61569905/6cb294ef-803a-4c2e-a8de-fa56010b8397)

**Comment by BunyaPineTree** [comment]
Make sure you're using the correct version of unity editor. I don't know what would cause this, but I know wrong version have caused similar problems in the past.

**Comment by NovaTheFurryDev** [comment]
i have 2022.3.9f1

**Comment by BunyaPineTree** [comment]
Closing this issue, as it's almost definitely related to an incorrect configuration.
