### ISSUE TITLE
[Feature Request] Add Whitelist support

### ISSUE THREAD

**Issue by Toys0125** [BunyaPineTree/LethalCompany_ModelReplacementAPI#109]
It makes it easier to share the zip files of friends' avatars they only want to use themselves.
Mainly for local installs of mods rather than uploading to the web.

**Comment by BunyaPineTree** [comment]
The mod is inherently clientside. I'm not sure what whitelisting would do, there's nothing stopping you from using different models from your friends.

**Comment by Toys0125** [comment]
The main issue is that everyone starts with the default orange suit, so I want to have only my player to have model replacement.

**Comment by BunyaPineTree** [comment]
That's some incredibly specific functionality you're asking for. I don't really have any reason to add that kind of function into the base API. 
It's possible for you to do that yourself, however. If you don't want anyone else using your suit, in the `LoadAssetsAndReturnModel` method of your model replacement class, add a clause that returns null if it detects that the player in question isn't the local player.

**Comment by Toys0125** [comment]
Thank you for telling me returning `null` is the correct way to do authentication, kinda wished your wiki had some details that explains what `LoadAssetsAndReturnModel` expects returns and behaves.
