### ISSUE TITLE
Joining a lobby as a client causes both you and the host's visor to dissappear.

### ISSUE THREAD

**Issue by Mr-Foxtrot** [BunyaPineTree/LethalCompany_ModelReplacementAPI#110]
No other mods, no errors or warning in the output log pertain to the mod. Bepinex and MRAPI only.

When a player joins the lobby, the visor in first person is missing for both the client and host. Once all clients leave the game the visor returns for the host.

**Comment by BunyaPineTree** [comment]
Thanks for the info. I'll give it a look when I have a moment.

**Comment by BunyaPineTree** [comment]
Thanks for the info. That's actually a really helpful clip, as it demonstrated both problems.

**Comment by ChronoIndeks** [comment]
Any info on that by now?

**Comment by BunyaPineTree** [comment]
This should be fixed as of the latest update. 

The post processing effects vanishing or flickering will keep happening if you're using a mod that adds third person, as third person perspectives usually remove the visor, and those post processing effects are inexplicably linked to the visor. 
Though that will only happen if you're in the third person perspective. It should be fine in first person.
