### ISSUE TITLE
[Suggestion] Toggle seeing your own model in first person

### ISSUE THREAD

**Issue by Tryflle** [BunyaPineTree/LethalCompany_ModelReplacementAPI#112]
I think it would be a good idea to add a toggle that lets you toggle between seeing your own characters model in first person. Here's what I mean:

In v2.3.8, you do not see your own model in first person:
![image](https://github.com/user-attachments/assets/d1869516-37ca-41e9-bbae-7c7000f0a1a1)
In v2.4.7, you do see your own model in first person:
![image](https://github.com/user-attachments/assets/8e648dad-83a9-43f6-9240-91f2dc52742d)

The reason I believe there should be a toggle is due to visual bugs with seeing your own models hands in first person and also due to camera obstruction. I preferred how it was on v2.3.8, but I'm sure many also prefer the way it is in v2.4.7, which is exactly why I think there should be an option of some sort that allows you to switch between these two modes. With the latest version, sometimes items I pick up disappear, look to be positioned wrongly or almost entirely obstruct my screen (Examples: Bee hive is invisible, stop sign is way too low, and large axle makes seeing incredibly difficult!).

Please do consider! This would be a great addition in my opinion. I'm not sure what adding this toggle entails, but I don't think it'd be too much effort. Thanks.

**Comment by BunyaPineTree** [comment]
The config option to turn them on or off was added when automatic viewmodels were added. 

First person viewmodels have been implemented for a considerably long while now as an experimental feature, just turned off by default. Given that I have received a grand total of zero complains about them not working, I think it's fair to turn them on by default from now on. If someone doesn't want to see a custom viewmodel, it's as simple as changing the config option via something like LethalConfig, taking the suit off, and then putting it back on.

**Comment by Tryflle** [comment]
Awesome, thanks for letting me know. My bad for not realizing in the first place. I know it isn't a huge bother, but I'm sorry to bother you by making this in the first place when it was already available and I somehow looked over it despite it clearly being advertised on the mod description. Sleep deprivation moment.
