### ISSUE TITLE
Slight incompatibility with MirrorDecor

### ISSUE THREAD

**Issue by MGJerry** [BunyaPineTree/LethalCompany_ModelReplacementAPI#113]
Hi, I ran into this problem where both the normal model and arm model is rendered in the mirror on all suits (normal suits and models that depend on this mod)
However, downgrading this mod back to 2.4.6 and before fixes this bug.
Modlist:
BepInEx-BepInExPack-5.4.2100
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.16.1
quackandcheese-MirrorDecor-1.3.2
BunyaPineTree-ModelReplacementAPI-2.4.7
BunyaPineTree-MikuModelReplacement-1.5.1

Edit: reporting here 'cause MirrorDecor's dev have been inactive for quite a while now...

![image](https://github.com/user-attachments/assets/b7b089d6-f818-4808-a68e-c9db0c4fd861)

**Comment by BunyaPineTree** [comment]
This is a known issue. The issue is that the rendering schema used by mirrordecor is incompatible with some emote mods, and just from the amount of community engagement I get, I've determined that it's a better idea to prioritize the emote mods working.

**Comment by MGJerry** [comment]
Aight, thanks for the clarification. I don't even use MirrorDecor much nowadays (since my group stuck to a specific subset of skin models) but it's nice to get a definite response.
