### ISSUE TITLE
Half the collisions dont work in v2.4.9

### ISSUE THREAD

**Issue by KKaydoom** [BunyaPineTree/LethalCompany_ModelReplacementAPI#118]
I landed on experimentation cant touch the monitors, the sides of the ship, the concrete platform on exp on the ship without falling through or walking through them.

**Comment by Salio24** [comment]
same

**Comment by ShadowWolf90** [comment]
Bump.

most of Colliders are not working on most maps.

**Comment by GaryYoung207** [comment]
Can confirm, this update caused me to fall through several areas (notably with ladders) including the ones on the ship, as well as the two ladders leading into experimentation.

**Comment by yoru-bat** [comment]
Hi! **Most colosseum models don't work.** The standard models of the game such as the Ship, platforms, and internal parts of the ship - monitors - have broken down. Containers in the company , pipes that lead to the doorway. As a complication of the game, it's cool, but it really bothers and bothers, **especially knowing that it shouldn't be like this.**

**Comment by Ylaaan** [comment]
Same issue here

**Comment by TrochiFranco** [comment]
same got to play on 2.4.8 then

**Comment by k1kere** [comment]
Yes! Hope it gets fixed soon, for now you can just run old version

**Comment by BunyaPineTree** [comment]
See the latest version.
