### ISSUE TITLE
REQUEST Video guide as its easy to get lost

### ISSUE THREAD

**Issue by The-Grace-God** [BunyaPineTree/LethalCompany_ModelReplacementAPI#12]
For me even though i tend to not like them very much a video guide on how to use this tool would be insanely helpful as i just got lost trying to follow the instructions (most likely because i don't use Visual Studio much).  I just got confused like making the "ExampleBodyReplacement" from the "BodyReplacementBase" as i didn't see anything relating to it in there.  I feel that a video tutorial even if its long and a bit repetitive would be really useful to people who are new to unity modding in general as some may have used the tools before but don't know how to do it the way that was intended or just don't even know how to use it at all.

**Comment by BunyaPineTree** [comment]
We are currently in the middle of a refactor that will replace the whole boneMap.json system with one that is done in the unity editor and a bit more accessible. I plan on putting out thorough documentation after that is done, but I personally can't guarantee a video guide.

**Comment by The-Grace-God** [comment]
@BunyaPineTree 
> We are currently in the middle of a refactor that will replace the whole boneMap.json system with one that is done in the unity editor and a bit more accessible. I plan on putting out thorough documentation after that is done, but I personally can't guarantee a video guide.

Oh nice that would probably help a lot especially for existing unity modders 
I do have a quick question though are custom shaders like poiyomi toon supported or is it only shaders the game currently uses

**Comment by BunyaPineTree** [comment]
Only the shader the game uses, HDRP/Lit. The mod will convert your material to the in game shader so it won't be transparent, but I don't know to what fidelity.

**Comment by The-Grace-God** [comment]
@BunyaPineTree 
> Only the shader the game uses, HDRP/Lit. The mod will convert your material to the in game shader so it won't be transparent, but I don't know to what fidelity.

so what your saying is stuff like this isn't possible
![image_2023-12-11_164526798](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/66783188/45dfd808-7326-4d65-a102-474c361cc7d2)

**Comment by BunyaPineTree** [comment]
Your best bet would be using the unity HDRP wizard to convert your materials to their HDRP counterpart and seeing where that gets you.

**Comment by BunyaPineTree** [comment]
Closing with reference to the wiki. If there's anything you want to see in there let me know.
