### ISSUE TITLE
Seems something isn't being defined. What can I do to fix this?

### ISSUE THREAD

**Issue by SillyCubeGuy** [BunyaPineTree/LethalCompany_ModelReplacementAPI#121]
[Error  : Unity Log] ArgumentNullException: Value cannot be null.
Parameter name: key
Stack trace:
System.Collections.Generic.Dictionary`2[TKey,TValue].FindEntry (TKey key) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].TryGetValue (TKey key, TValue& value) (at <787acc3c9a4c471ba7d971300105af24>:0)
ModelReplacement.BodyReplacementBase.LoadModelReplacement () (at <2793bce476bf4bf382bb2e8ffa83831b>:0)
ModelReplacement.BodyReplacementBase.Awake () (at <2793bce476bf4bf382bb2e8ffa83831b>:0)
UnityEngine.GameObject:AddComponent(Type)
ModelReplacement.ModelReplacementAPI:SetPlayerModelReplacement(PlayerControllerB, Type)
ModelReplacement.PlayerControllerBPatch:ManageBodyReplacements(PlayerControllerB)
ModelReplacement.PlayerControllerBPatch:ManageRegistryBodyReplacements(PlayerControllerB&)
GameNetcodeStuff.PlayerControllerB:DMD<GameNetcodeStuff.PlayerControllerB::Update>(PlayerControllerB)

**Comment by BunyaPineTree** [comment]
This is materials related, it usually means that some material your model uses didn't get packaged into the assetbundle. I don't think there was ever a good reason found for this bug, but it's probably related to how your imported your model. Make sure to export your materials and textures from the model, if possible.
