### ISSUE TITLE
Strong error spam

### ISSUE THREAD

**Issue by Paradox75831004** [BunyaPineTree/LethalCompany_ModelReplacementAPI#125]
Recently, one mod has been installed with them

![image](https://github.com/user-attachments/assets/9bb30af8-050b-471d-bf25-1dd47434de58)

![image](https://github.com/user-attachments/assets/5d4f665e-4c86-421b-8e74-e2b952e1dce5)

**Comment by BunyaPineTree** [comment]
Solution's simple. Don't use UDA. There's never a reason to use UDA.

**Comment by Paradox75831004** [comment]
> Решение простое. Не используйте UDA. Никогда не бывает причин использовать UDA.

What is UDA?
