### ISSUE TITLE
Outfits Bug?

### ISSUE THREAD

**Issue by ThighHighSockGod** [BunyaPineTree/LethalCompany_ModelReplacementAPI#16]
In the CFG file i added the other suits for the model yet in the game the suits don't show, and the More Company Cosmetics didn't show.
https://imgur.com/a/eRzXFLs
https://imgur.com/a/pJFPh6Y

Edit: The Cosmetics do work but in first person some cosmetics are able to be seen or hovering, and when using the Emotes from more Emotes the Character is invis.
https://imgur.com/a/BKGoDz5
https://imgur.com/a/d67o2jw
https://imgur.com/a/TzbZxXy

**Comment by BunyaPineTree** [comment]
Testing this particular set of issues has been a nightmare, but with the recent commit I've put together a renderer layer / cullingmask system that may resolve the fundamental issues. 

Will do more testing and close if it seems resolved.

**Comment by BunyaPineTree** [comment]
Should be fixed with the latest release
