### ISSUE TITLE
[2.3.1] Pink overlay on barriers

### ISSUE THREAD

**Issue by Edouard127** [BunyaPineTree/LethalCompany_ModelReplacementAPI#22]
The texture for the barriers have a pink overlay when replacing models
I do not know what causes this issue, but it's not related to my mod as I don't mess with textures
![image](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/46357922/15574c0c-bd9a-463f-b476-d960cd253b8c)

Mod that could cause compatibility issue: MoreCompany, LethalExpansion

Lastest game version
Windows 10 19045.3693
AMD Ryzen 7 5700X 8-Core
Radeon RX 5500 XT

**Comment by BunyaPineTree** [comment]
This is a result of no post processing layers being put on the camera, I mistakenly decided on a layer that had no gameobjects in the ship, when it had gameobjects on the moon. 

This issue has already been fixed and will be out on the next update.
