### ISSUE TITLE
Usernames not showing up with deferent player models  

### ISSUE THREAD

**Issue by Yeetyboi2000** [BunyaPineTree/LethalCompany_ModelReplacementAPI#23]
Without custom player models (I still have client-sided mods)
![20240104113348_1](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/155671410/75555a8e-2440-4f13-911e-71e31db3cfe3)

With custom player models
![20240104113610_1](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/155671410/01673806-2f9a-4e50-b211-1de49718f6e4)

another modded screenshot
![20240104113628_1](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/155671410/98a90403-a679-4af3-ad19-0b17637e3121)

It does the same even with different player models too.
I also checked the other mods that might have been causing the problems but even after removing those the problem continues

**Comment by BunyaPineTree** [comment]
Funnily enough the crew member mod came out before I started working on the API and I don't believe it depends on it. 
I am currently working on a fix for the issue, and I'll release it with a number of other fixes after it is working.
