### ISSUE TITLE
v2.3.2 incompatible with More Suits

### ISSUE THREAD

**Issue by 1RV34** [BunyaPineTree/LethalCompany_ModelReplacementAPI#24]
After updating to v2.3.2 all [More Suits](https://thunderstore.io/c/lethal-company/p/x753/More_Suits/) suits are invisible.

v2.3.1 does not have this issue.

**Comment by Edouard127** [comment]
This happened to me twice while I was dual testing the game, restarting the game fixed the issue

**Comment by BunyaPineTree** [comment]
Thanks for the info. Trying to get all of the camera mods to work together is quite the nightmare.

**Comment by Edouard127** [comment]
![image](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/46357922/123efbf4-39f7-4152-b5d9-1b20c114535c)
![image](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/46357922/88437cae-4fa2-468c-9ebc-37bad76123be)

New behavior, happens from time to time

**Comment by 1RV34** [comment]
> This happened to me twice while I was dual testing the game, restarting the game fixed the issue

I got a group of people to test with, we've tested about 4 different versions, only version changes affected our issue, restarting the game did not.

> Thanks for the info. Trying to get all of the camera mods to work together is quite the nightmare.

Oh yeah, I bet! But in my case we don't have any camera mods installed. I'll probably be able to do a test with a minimal mod set tomorrow to provide a narrowed down testcase.

> ![image](https://private-user-images.githubusercontent.com/46357922/294618146-123efbf4-39f7-4152-b5d9-1b20c114535c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0OTY3NDIsIm5iZiI6MTcwNDQ5NjQ0MiwicGF0aCI6Ii80NjM1NzkyMi8yOTQ2MTgxNDYtMTIzZWZiZjQtMzlmNy00MTUyLWI1ZDktMWIyMGMxMTQ1MzVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDIzMTQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0M2M2NTIyMmY1MWY1YjYzMTE4MDUyZDAzN2YxOGQ5OTI1MDA1YzcwMTFkODdkMGI1ODc1NzI4M2ExNWE3NmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9WRmtIRay2leE6kVS9e0tKmbqlfQCKg0SbswKy9bkNU) ![image](https://private-user-images.githubusercontent.com/46357922/294618188-88437cae-4fa2-468c-9ebc-37bad76123be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0OTY3NDIsIm5iZiI6MTcwNDQ5NjQ0MiwicGF0aCI6Ii80NjM1NzkyMi8yOTQ2MTgxODgtODg0MzdjYWUtNGZhMi00NjhjLTllYmMtMzdiYWQ3NjEyM2JlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDIzMTQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwMzRiMTQ0Y2YzMDNjMmMzYjU5NzEyNDhlODE1ZDcxZjgzYWYyODkwMjYzYjVhMzBkZjc5NTM4ZmYwZThhMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yrl4lwrv8PuiRvXfndwVk5-e8rYOQrnGpguIEUQuT5c)
> 
> New behavior, happens from time to time

This looks like a different issue, in our case the extra suits are completely invisible.

**Comment by BunyaPineTree** [comment]
Yep, I'll see if I can't get this one out by the end of the night now that I'm free. 
The issue is that in reconciling all of the third person and camera mods, I have to change a lot of things to uniformity, and there are always cases that I won't see.

**Comment by BunyaPineTree** [comment]
I've put out an update to thunderstore. Let me know if it works correctly.

**Comment by SilberComic** [comment]
still invisible for me

**Comment by 1RV34** [comment]
> I've put out an update to thunderstore. Let me know if it works correctly.

Hey!
We just updated to v2.3.4, with this version the invisible More_Suits suits seems to have been fixed!

With it, it also seems that a second issue has also been fixed!
We were no longer seeing name tags with [NameplateTweaks](https://thunderstore.io/c/lethal-company/p/taffyko/NameplateTweaks/), but we had not yet hunted down whether that was a LethalCompany_ModelReplacementAPI at all or something else.

Thank you for your support!

**Comment by Edouard127** [comment]
You cannot see yourself in the ship camera
Really small detail

![image](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/46357922/a386478b-dfb2-4fff-97f4-27c37ba8fc61)
![image](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/46357922/5f28fa4d-168f-4d23-9c41-550ba2452a7f)
