### ISSUE TITLE
[2.3.4] Makes Default Model glitch out

### ISSUE THREAD

**Issue by Xenoreaper** [BunyaPineTree/LethalCompany_ModelReplacementAPI#29]
Simply adding this API makes the default character model have weird polygons stretching along most body parts.

Arms on 2.3.2
![image1](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/49926609/6ccd206d-f3b9-4209-b048-34aad0ebee74)
Helmet on 2.3.2
![image2](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/49926609/86940952-61e0-43b9-a155-9fa7bcb161aa)
Legs on 2.3.2
![image3](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/49926609/395a8417-0838-4292-a6cc-1bd0b9462d9d)
Arms on 2.3.4
![image4](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/49926609/b4ed3d09-7c2d-4ffa-8e74-da5743489072)
(The first 3 images are from V2.3.2 but still look the same on V2.3.4)

**Comment by BunyaPineTree** [comment]
Could you tell me the circumstances that this image came from? Is it yourself or someone else? Is this before or after putting on a model replacement, is this just in the ship or also on a moon, does it go away after going a distance from the other person and returning, etc...
Finally what other mods are you using? This has to do with Level Of Details, which should be handled by the game.

**Comment by Xenoreaper** [comment]
Great Questions, I'll test some more tomorrow and get you some more info on that.
What I can say right now is that it is without any model replacements at all, just the API.

**Comment by BunyaPineTree** [comment]
I believe this has been corrected, so closing.
