### ISSUE TITLE
Project uses json to set bones, instead of API

### ISSUE THREAD

**Issue by alekso56** [BunyaPineTree/LethalCompany_ModelReplacementAPI#3]
Unity has built in api for humanoid setups to fetch bone information
example, on prefab root object where animator resides: 
Transform hipsbone = root.GetComponent<[Animator](https://docs.unity3d.com/ScriptReference/Animator.html)>().[GetBoneTransform](https://docs.unity3d.com/ScriptReference/Animator.GetBoneTransform.html)([HumanBodyBones](https://docs.unity3d.com/ScriptReference/HumanBodyBones.html).Hips);

This allows you to directly access the model bones without knowing their names etc.
i don't think this project should support non humanoid structures.

you might need to add a dependency to `UnityEngine.AnimationModule.dll`

**Comment by BunyaPineTree** [comment]
This is now officially how model replacements are handles, and will be on thunderstore once everybody who has published a mod has had a chance to make the change.
