### ISSUE TITLE
[Idea] Internal variables view access

### ISSUE THREAD

**Issue by Edouard127** [BunyaPineTree/LethalCompany_ModelReplacementAPI#30]
Developers cannot easily know if a player currently have a custom model on them
It's a good idea to make such variables accessible without necessarily allowing them to be modified

Ex:
```
ViewStateManager manager = <PlayerControllerB>.gameObject.GetComponent<ViewStateManager>()

manager.HasBodyReplacement() => returns bool
manager.UsesNoPostProcessing() => returns bool
```

This will make the development of certain mods way easier

**Comment by BunyaPineTree** [comment]
I will add the following methods to the ModelReplacementAPI class static methods. 
```public static bool GetPlayerModelReplacement(PlayerControllerB player, out BodyReplacementBase modelReplacement);
public static bool GetPlayerModelReplacement(PlayerControllerB player);
```
Note that all I'm doing is `modelReplacement = player.thisPlayerBody.gameObject.GetComponent<BodyReplacementBase>();`, as the existence of a `BodyReplacementBase` on the `PlayerControllerB` gameobject is all that is needed to determine a model replacement.
