### ISSUE TITLE
v. 2.3.4 visual bug with Too Many Emotes

### ISSUE THREAD

**Issue by sammaxis** [BunyaPineTree/LethalCompany_ModelReplacementAPI#31]
Whenever one tries to use an emote with Too Many Emotes, when you enter the 3rd person view, you will see a visual bug with floating arms. This does not happen if other players use emotes. Only yourself. This has only been an issue the past couple of days so one of the latest updates seems to have caused this issue.

https://imgur.com/a/4IV0OPF

**Comment by BunyaPineTree** [comment]
Are you using any other mods alongside? As I showed in that image I sent earlier, that simply hasn't been my experience, so I'm having trouble tracing the issue.

**Comment by sammaxis** [comment]
Thjis is now fixed in 2.3.5. Thanks!
