### ISSUE TITLE
Will cause player vanish over meters away. Including name.

### ISSUE THREAD

**Issue by XKaguya** [BunyaPineTree/LethalCompany_ModelReplacementAPI#33]
As title.
![A40G8 OLL 64{ZR`2KAEDDF](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/96401952/3e9514be-d2de-4aed-b274-a6a722d53bae)

Like this.

Before update its nomal. But at version 2.3.4 it happened.
Nomatter you are a custom skin or default, It will always happen.

**Comment by Edouard127** [comment]
Same behavior here

**Comment by FirewallDaProtogen** [comment]
same behaviour
all suits that arent the replaced model become invisible when a slight distance away

**Comment by BunyaPineTree** [comment]
See the recent update on thunderstore.

**Comment by Edouard127** [comment]
Issue is fixed

**Comment by BunyaPineTree** [comment]
Closing as resolved
