### ISSUE TITLE
2.3.5 Models other than the Hololive ones become invisible

### ISSUE THREAD

**Issue by Andrew13421** [BunyaPineTree/LethalCompany_ModelReplacementAPI#34]
The title. Also it works perfectly fine on version 2.3.4 but version 2.3.5 broke the hololive mod. You probably already know about this but I'm making this thread since no one else here pointed it out.

**Comment by Andrew13421** [comment]
Also I forgot to mention the other suit mods I have enabled:
Waluigi suit by Team_Waluigi
Longnose_Anime_Suits by Chrispacito
TooManySuits by Verity
Low_Budget_One_Piece_Suits by OnePeak
FNAF_Suits by Festive_Arms

**Comment by BunyaPineTree** [comment]
I have heard that the LODs aren't working other than the close range ones for the regular character, but the hololive mod breaking is new to me. Can you describe what about it has broken?

**Comment by Edouard127** [comment]
Same behavior here
When a player doesn't have a custom model, it disappears a meter away

**Comment by Jwaffled** [comment]
I am also experiencing a similar issue. Perhaps [this change](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/commit/5218f5117142bdb19e0d086cb53abcf3838e1644#diff-9f03833d27cae5f61c1db5d52564e78affce63f50c9f9fb33d5f23fe3aef8b60R334) is suspect?

**Comment by BunyaPineTree** [comment]
Yes, I'm fairly certain that change is the issue and has to do with the LOD controller fighting with my ViewStateManager. Now that I'm free I'll test an alternative that was working in the past.

**Comment by BunyaPineTree** [comment]
See the recent update on thunderstore.

**Comment by Edouard127** [comment]
Issue is fixed

**Comment by BunyaPineTree** [comment]
Closing as resolved
