### ISSUE TITLE
[2.3.5] [Medium] GetPlayerModelReplacement throw an exception on spectated player online

### ISSUE THREAD

**Issue by Edouard127** [BunyaPineTree/LethalCompany_ModelReplacementAPI#36]
When spectating a player online, `ModelReplacementAPI.GetPlayerModelReplacement` throws a null reference on `<PlayerControllerB>.spectatedPlayerScript`
This only happens in online games, when playing in LAN, no errors are thrown

```
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ModelReplacement.ModelReplacementAPI.GetPlayerModelReplacement (GameNetcodeStuff.PlayerControllerB player, ModelReplacement.BodyReplacementBase& modelReplacement) (at <dc9efcd8a17e42459dca9d316f1c68f4>:0)
LethalWarfare2.Modules.PlayerControllerBPatch.GetBoneTransform (GameNetcodeStuff.PlayerControllerB __instance, System.String bone) (at <89cb64fa2320445395fe058643ad76b5>:0)
LethalWarfare2.Modules.PlayerControllerBPatch.RaycastSpectateCameraAroundPivot (GameNetcodeStuff.PlayerControllerB& __instance) (at <89cb64fa2320445395fe058643ad76b5>:0)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::RaycastSpectateCameraAroundPivot>(GameNetcodeStuff.PlayerControllerB)
GameNetcodeStuff.PlayerControllerB.LateUpdate () (at <44743d9474784365a095189c76175301>:0)```

**Comment by Edouard127** [comment]
Maybe the fact that the local player model is destroyed on death causes this issue

**Comment by Edouard127** [comment]
Checking the spectated player body animator also throws an error so maybe this is not library related

```
[Error  : Unity Log] InvalidOperationException: Avatar is null.
Stack trace:
UnityEngine.Animator.GetBoneTransform (UnityEngine.HumanBodyBones humanBoneId) (at <5d72b68986b04a96815303374320f4d3>:0)
LethalWarfare2.Modules.PlayerControllerBPatch.RaycastSpectateCameraAroundPivot (GameNetcodeStuff.PlayerControllerB& __instance) (at <1caa6826d2e541648f595bf8787c9763>:0)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::RaycastSpectateCameraAroundPivot>(GameNetcodeStuff.PlayerControllerB)
GameNetcodeStuff.PlayerControllerB.LateUpdate () (at <44743d9474784365a095189c76175301>:0)
```
```
Transform boneRig = __instance.spectatedPlayerScript.playerBodyAnimator.GetBoneTransform(HumanBodyBones.Head);
```

**Comment by Edouard127** [comment]
I think this has to do with how the game was coded and how the networking is in the game, but there are still animations over the server so this is a really weird behavior

**Comment by BunyaPineTree** [comment]
That's a good catch. Calling `player.thisPlayerBody.gameObject.GetComponent<BodyReplacementBase>();` is from the earlier renditions of the API before I had a solid understanding of how things were laid out. I'll try an alternative that accounts for thisPlayerBody being null. Let me know how that affects your mod.

**Comment by Edouard127** [comment]
Basically in my mod I need to get the spectated player's bone position

**Comment by Edouard127** [comment]
`StartOfRound.Instance.OtherClients`, `StartOfRound.Instance.allPlayerScripts` both have a null player body animator online, some people though it was a compatibillity issue with MoreCompany but it wasn't
I'm getting desperate on this bug
Is it possible to set the PlayerControllerB model via rpc ?

**Comment by Edouard127** [comment]
After some deeper debugging, someone told me that the player body animator isn't null, the Avatar is
So this might be a bug with the library and not the game

https://docs.unity3d.com/ScriptReference/Animator.GetBoneTransform.html

**Comment by BunyaPineTree** [comment]
I'll be putting out the update I mentioned shortly. Note that I do not use the player Animator, I get those bones directly forrm the skinnedmeshrenderer, and the Animator on the model replacement is not destroyed in death, only on revival.

**Comment by BunyaPineTree** [comment]
The update is on thunderstore.

**Comment by Edouard127** [comment]
Fixed
