### ISSUE TITLE
Why Opaque render mode only?

### ISSUE THREAD

**Issue by akronmna1** [BunyaPineTree/LethalCompany_ModelReplacementAPI#38]
How to apply other render modes? I can't use other because my model completly disapear.

**Comment by BunyaPineTree** [comment]
This is a unity issue, not an API issue. I haven't had any issue with transparency in my models.

**Comment by akronmna1** [comment]
What settings and shaders did you have set to use transparency?

**Comment by BunyaPineTree** [comment]
First of all it has to be an HDRP supported shader, and you have to have a 3D HDRP unity project. If you are using the standard shader or an unsupported one like poiyomi it will be converted to HDRP in the simplest way possible in game, which does not include transparency. After that I believe it's just Render Mode: Transparent on your materials.

**Comment by akronmna1** [comment]
Oh, ok. Thanks for this. But can you suggest me shaders with HDRP support? I just haven't encountered this and usually HDRP is not used in VRChat.

**Comment by BunyaPineTree** [comment]
If your model uses cell shading I would recommend LilToon for the time being. Its lighting is a bit incorrect, and you definitely need to fine tune some parameters, but it does a good job. Incidentally it's also what I use on Miku.

**Comment by akronmna1** [comment]
I've already tried liltoon. Idk why but opaque only works, other render modes makes my model fully transparent

**Comment by BunyaPineTree** [comment]
Unfortunately I don't know enough about 3d modeling to help you in that case. Perhaps investigate your issue under the context of how unity handles transparency.

**Comment by akronmna1** [comment]
Thanks. I was making models in default 3d project. It is was issue.
Now I have no problems with render modes.
