### ISSUE TITLE
Ideas for The Api

### ISSUE THREAD

**Issue by Lycranok** [BunyaPineTree/LethalCompany_ModelReplacementAPI#40]
I'm not sure if its possible but a great feature to add is the ability for other people if they have the api to load custom models without the need of downloading the model, but im not sure how feasible that is with the current tools

**Comment by Edouard127** [comment]
I don't think that's remotely feasible with the implementation of the networking in the game
And this library is client side only

**Comment by Edouard127** [comment]
And this can be abused by extremely large models, for example I have a 3d model that is 140 mb in size
Also usually it is not a good idea to p2p files in a game as it can be manipulated for remote execution

**Comment by BunyaPineTree** [comment]
If we ignore all of the above issues, that could very easily be used to show people things they do not want to see. For the foreseeable future, your best bet is to distribute a modpack that has already assigned all of the models you want to the suits you want.
