### ISSUE TITLE
Different Models Simultaneously?

### ISSUE THREAD

**Issue by AndrewHKGithub** [BunyaPineTree/LethalCompany_ModelReplacementAPI#48]
Hi, first off, thank you so much for creating an API that is so excellent and an in-depth tutorial on how to use it, even as someone with no experience in Blender, Unity, or with coding I have been able to make several mod packages that function in game and online.

My question is, how exactly do you get a single build with multiple replacement models? Using the Miku example mod as a reference, I was able to get the two model replacements I made to replace the Hazard suit and the Green suit, but I don't know how to go about having them running simultaneously so I can have a single lobby where one model replaces the green suit, and another replaces the hazard suit. When I rename one of the "Build" folders in my plugin folder, Lethal crashes on the menu screen. Judging by the TF2 example, I'm supposed to have a single package with multiple models in it, but I'm not sure how to do that.

Thank you again for your great service to the community.

**Comment by BunyaPineTree** [comment]
I'm assuming that you are asking about having a single .dll file that has multiple model replacements for different suits. If that assumption is incorrect please let me know. 

The idea of the project workflow I setup was to be able to link multiple prefabs to a single project and have them build into a single assetbundle for use in your mod. 
In practice, this would involve dragging your mod's project onto the Project field of both of the prefabs you have setup for use in ModelReplacementAPI, which would link both of the prefabs to it, then when you generate the files for that project it would create the BodyReplacement classes for both of your prefabs. 
After that, actually registering your BodyReplacement classes to the two suits you want is up to you. You could take inspiration from the Miku/Evil Miku config options, or you could just register it directly to "Green Suit" and not have a config at all. 

Again, if I misunderstood you then let me know, and I am not sure what you mean by renaming the "Build" folder in your plugin folder.

**Comment by AndrewHKGithub** [comment]
You assume correctly, so basically I need to 

1. have one Unity 3D HDRP project open, 
2. import and rig all the models I want to use in the single .dll, 
3. set up both models as prefabs separately using ModelReplacementSDK/Setup Model, 
4. create a model replacement sdx project,
5. drag that project into the project fields of BOTH prefabs
6. continue as normal and use the miku config as reference to assign different models to different suits

**Comment by BunyaPineTree** [comment]
Sounds correct.

**Comment by AndrewHKGithub** [comment]
Works perfectly, thank you so much.
