### ISSUE TITLE
Wrong size

### ISSUE THREAD

**Issue by huluoboya3** [BunyaPineTree/LethalCompany_ModelReplacementAPI#49]
When using mods made by the LethalEmotesAPI, changing clothes while Emotes is in progress will result in incorrect sizes.
After stopping the operation, switch again to restore normal.
use mod：
-more suit1.4.1
-modelreplacementapi2.3.6
-mashumodel1.0.5
-LethalEmotesAPI1.2.4（It was the same in previous versions）
lethalcompany_inpututils0.5.5
lethalconfig1.3.4
BadAssCompany1.1.0

video：
https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/93986295/37eeb292-65b0-4f50-b411-2ad5e77e0771

**Comment by BunyaPineTree** [comment]
Thank you for the report. There are actual similar issues relating to this bug that I have been researching how to fix, so a fix is on its way.

**Comment by BunyaPineTree** [comment]
This should be fixed in the latest release.
