### ISSUE TITLE
Model won't show in MoreSuits rack in game.

### ISSUE THREAD

**Issue by Honua** [BunyaPineTree/LethalCompany_ModelReplacementAPI#50]
Hi! Sorry if this isn't really an issue, I very well might just be doing something wrong.

If I set my model to load as the default it appears to load fine. However, I'm trying to get the model replacement to show up as a suit in the rack that comes with the more suits mod. 

Right now I have: 

ModelReplacementAPI.RegisterSuitModelReplacement("SigmaOverwatch", typeof(MRSIGMA)); 
-----> Found within the awake function. I assumed that was all I had to do but I feel like I'm missing something important that I can't find anything about. I tried to look at how other mods did it and I have it set up in the same format.

Thanks again for any help, and sorry if this isn't the right place to post this!

**Comment by Honua** [comment]
Figured it out!

**Comment by Edouard127** [comment]
Can you tell how for future issues like this

**Comment by Honua** [comment]
Yeah, I honestly felt stupid and it's fairly embarassing, but basically you have to read the documentation for MoreSuits. I didn't realize that basically you have to add a suit with a name using the moresuits mod first, then "override" that suit by name with ModelReplacementAPI.
