### ISSUE TITLE
Jiggle Physics

### ISSUE THREAD

**Issue by FuttBucker3000** [BunyaPineTree/LethalCompany_ModelReplacementAPI#56]
I was wondering if you used the unity jiggle physics that come with the model replacement sdk , and if you did, what settings did you use for the miku example. I'm trying to implement basically the same jiggle physics to the hair that the miku example had to another miku model.

**Comment by BunyaPineTree** [comment]
Here's my settings. 
[mikuJiggleSettings.zip](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/files/14004059/mikuJiggleSettings.zip)

**Comment by BunyaPineTree** [comment]
I assume this is concluded.
