### ISSUE TITLE
v1.4.1: Odd 3rd-person behavior

### ISSUE THREAD

**Issue by Haano137** [BunyaPineTree/LethalCompany_ModelReplacementAPI#6]
Attached bellow are the log file and video.

[LogOutput.log](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/files/13624219/LogOutput.log)
https://streamable.com/7bzhyh

**Comment by BunyaPineTree** [comment]
I'll look to adding MirrorDecor support after current priorities are taken care of. Thanks for the report.

**Comment by BunyaPineTree** [comment]
Closing thanks to Adamasnaldo's PR#17. Note that there is still some funny business with LCThirdPerson
