### ISSUE TITLE
Having 19845 errors with the code CS0246 and CS0616

### ISSUE THREAD

**Issue by HinaKagiyama** [BunyaPineTree/LethalCompany_ModelReplacementAPI#61]
It's my first time using a IDE, so i'm veeery lost on this.
I followed the tutorial from start to end, and when i want to rebuild, it gets filled with CS0246 and CS0616 errors, naming the files "ReadmeEditor.cs", "BodyReplacement.cs", "ItemOffsetEditor.cs" and etc.
Tried to search for a solution on google, even talking with a friend that knows about this kind of thing, but we didn't find a solution.

**Comment by EstEsc282** [comment]
I'm having the same issue and I don't know what to do either.

**Comment by BunyaPineTree** [comment]
Judging from the files you mentioned, I can only assume you put your visual studio project in your unity project, or vice versa. 
Make sure to put your VS project outside of your unity project, as visual studio can't compile your unity scripts, and unity can't compile your visual studio scripts.

**Comment by Clb184** [comment]
Hello, Hina and me have been looking into this today and finally got it working fine, so I guess we can mark this as solved.
