### ISSUE TITLE
Missing files and new ones (I have zero clue what went wrong...)

### ISSUE THREAD

**Issue by Astral-Trinity** [BunyaPineTree/LethalCompany_ModelReplacementAPI#62]
Followed guide and even video guide both have resulted in the same problem.
no templatebundle nor anything similar was created.

Each time i double click the csproj an obj folder appears same with a bin... not sure if that is supposed to happen.

multiple files not shown in the guide appear such as BodyReplacements.cs.meta build.meta plugin.cs.meta csproj.meta

![image](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/52015366/57e22065-1e99-49ef-b2f3-316176fdbc3f)

and each time I run it... it fails.

![image](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/52015366/93841a98-5f56-4a66-8b1d-0d81347309c8)
![image](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/52015366/dc6bafea-b58e-4934-aacb-195c8b7a37c3)
![image](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/52015366/a52bec82-7e89-4f4e-9a06-e08bdd9eae11)

I have no clue what is wrong. I have the unity stuff exported as per the guide and as per the video both never generated the bundle files and at this point I wonder if I missed despite having retraced my steps twice...

**Comment by BunyaPineTree** [comment]
First of all did you link your model replacement project to your prefab? You can know this to be the case if in your model replacement project, there is a scene prefabs or hierarchy prefabs section that includes your prefab. 
If that isn't the case, make sure to link them by dragging the project into your prefab's project field. The location of which can be found in the wiki. 

Second, if you set your visual studio project location to be somewhere in your unity project, visual studio will not be able to compile the unity scripts, and unity will not be able to compile the visual studio scripts, so you should place your project elsewhere, and delete everything that was already generated in the unity project. 

Finally, there have been a few isolated instances where people have been completely unable to build assetbundles at all in their unity project, unrelated to the SDK. If everything mentioned has already been resolved and you still have this issue you may want to just make a new unity project

**Comment by Astral-Trinity** [comment]
I had forgotten to show the screenshot about my project settings in unity, well it was already linked and working fine in that regard.

having gone through it, it appears that the location I chose was related to unity and failed due to the situation you said. I apologize having taken your time, I should have taken that info from the previous issue and and attempted that. my tired mind had caused something unnecessary.

![image](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/52015366/0278529d-b562-47ab-ac40-c7bca7932933)

Thanks again for your help.
