### ISSUE TITLE
Floating head shadow

### ISSUE THREAD

**Issue by TonyZeit** [BunyaPineTree/LethalCompany_ModelReplacementAPI#66]
I just found out this mod (https://thunderstore.io/c/lethal-company/p/Woecust/Immersive_Visor/) would cause head shadow reappear.
![20240206155420](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/133832953/ba471e00-b2fb-44c1-bab9-9aeaa47d0017)

**Comment by TonyZeit** [comment]
I don't think we need to fix it though.

**Comment by BunyaPineTree** [comment]
Thanks for letting me know. As of this moment I have yet to find a way to make shadows work in both third person and first person, so until then I'll be leaving this issue as it.

**Comment by BunyaPineTree** [comment]
Closing because shadows will be fixed in the next release. 

That helmet shadow will still be there if you have the HUD enabled, I haven't found a way to separate that helmet shadow and the HUD, but the actual character shadow should cover it up for the most part.
