### ISSUE TITLE
A Problem on Replacing Enemy Models

### ISSUE THREAD

**Issue by TShineCN** [BunyaPineTree/LethalCompany_ModelReplacementAPI#67]
Could you please spare some time to kindly offer some guidance? 
I successfully replaced the enemy's model by disabling the original enemy's skinnemeshrender and then loading my own skinnemeshrender. But I found that there are significant issues with the enemy's animation, often with completely reversed hands or legs. I have no idea where the problem lies now. The bone weights, orientation, and animation in Unity are all fine,I don't know how to solve this problem.

I use EvaisaDev's Unity project to create custom assets【https://github.com/EvaisaDev/LethalCompanyUnityTemplate】

**Comment by TShineCN** [comment]
In the original game, AnimContainer has a rig file in addition to the bones, which seems to have some settings for the bones of the legs and arms. I don't know what they do.

![1111111](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/54096173/61e98329-db05-437d-a69a-26111b175622)

**Comment by BunyaPineTree** [comment]
Those Rig files you're seeing are IK targets, to my knowledge. IK is typically handled with an entirely separate armature guiding the base model armature, and you don't need to worry about it. We are interested in copying the metarig rotations. 

The problem of reversed hands, legs, and whatnot is not a new issue, and is the reason why the SDK exists to begin with. Bone rotations are encoded with quaternions, which can face in a direction as well as have an axial twist. There's no way of determining the correct twist from the model bone to the player bone, so rotation offsets are calculated for each bone when you setup a model in the SDK. (using a dummy playermodel for reference) 
Those offsets are multiplied on top of the actual in-game player bone rotation, and then set as the model replacement bone rotation, to achieve the correct animation of the model replacement. 

The code for the SDK is somewhat convoluted as it was not designed to be understandable by people making use of the API, but you can see how I achieved the bone rotation offsets there. 
Something of note is that bone rotation offsets are only accurate if your model and the replacement model are in as close to the same pose as possible. I ensure this by using the Humanoid Avatar standard T-Pose position.

**Comment by TShineCN** [comment]
> Those Rig files you're seeing are IK targets, to my knowledge. IK is typically handled with an entirely separate armature guiding the base model armature, and you don't need to worry about it. We are interested in copying the metarig rotations.
> 
> The problem of reversed hands, legs, and whatnot is not a new issue, and is the reason why the SDK exists to begin with. Bone rotations are encoded with quaternions, which can face in a direction as well as have an axial twist. There's no way of determining the correct twist from the model bone to the player bone, so rotation offsets are calculated for each bone when you setup a model in the SDK. (using a dummy playermodel for reference) Those offsets are multiplied on top of the actual in-game player bone rotation, and then set as the model replacement bone rotation, to achieve the correct animation of the model replacement.
> 
> The code for the SDK is somewhat convoluted as it was not designed to be understandable by people making use of the API, but you can see how I achieved the bone rotation offsets there. Something of note is that bone rotation offsets are only accurate if your model and the replacement model are in as close to the same pose as possible. I ensure this by using the Humanoid Avatar standard T-Pose position.

Thank you very much for your guidance!!!
I also used Humanoid Avatar standard T-Pose position.But there is still this problem.I will try what you said and try to ensure that the replacement model matches the original model and bone position as much as possible

**Comment by BunyaPineTree** [comment]
If you are using the model replacement generated by the SDK for player characters then this is expected, Dress Girl and Scavenger have different armatures after all.

**Comment by BoredBean** [comment]
Wait, are you already using this API for enemy models?

**Comment by BunyaPineTree** [comment]
After working out masked, I realized that there are already lots of enemy replacement mods out there, and an API isn't really needed.
