### ISSUE TITLE
Incompatibility with MoreCompany? Exception issue

### ISSUE THREAD

**Issue by VioletXe** [BunyaPineTree/LethalCompany_ModelReplacementAPI#68]
This happens when putting on the Black Dragon outfit. Don't know if it occurs with others, but the exception spam caused some severe lag for my friends.
![image](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/157070685/6af2d0a7-9168-4017-9a09-bf7ee1d72a78)

**Comment by BunyaPineTree** [comment]
This is a known issue, and has been dealt with on experimental builds, but won't be addressed until the next update that introduces some changes to how MoreCompany cosmetics are handled.

**Comment by ZhuJap** [comment]
+1111111111111111111111 Brother, encountering the same problem as you will cause the log text size to expand infinitely.

**Comment by ZhuJap** [comment]
Brother, encountering the same issue as you will cause the log file size to increase infinitely.

**Comment by BunyaPineTree** [comment]
The exceptions should be fixed in the latest release, though MoreCompany cosmetics themselves are not, as that will also require changes to the SDK.
