### ISSUE TITLE
The AssetBundle 'IO.Stream' can't be loaded because another AssetBundle with the same files is already loaded.

### ISSUE THREAD

**Issue by Callff** [BunyaPineTree/LethalCompany_ModelReplacementAPI#74]
I made one mod, works flawlessly. Made a second mod, also works flawlessly. When I try putting them in the same profile however, I get this error in console and in-game only the first-loaded mod works. In this scenario, the second mod I made will load models, but the first one I made will just apply the custom suit textures I made for the suit rack (not the models). If I remove the second mod I made, the first mod will start working again and loading models properly. Am I doing something wrong or is this a bug? I don't really understand how there can be any conflicts. The first mod I made is installed via thunderstore download while the second one (the one I'm currently working on) is installed locally into thunderstore. I also have other people's modelreplacementapi mods installed too, and those don't have issues, so I can't figure out what the problem is.

**Comment by Callff** [comment]
Found the issue - when I added more models and rebuilt the project it didn't add the classes to BodyReplacements.cs. I had added them myself (and it worked), but I guess that must not have been the only thing it didn't do because through my troubleshooting I generated a new project and it _did_ add the classes this time, and now there's no more conflicts.

**Comment by BunyaPineTree** [comment]
Just so you are aware, that bug almost always means you did not change the assetbundle name from templatebundle. 
As a limitation of the system unity uses to manage assetbundles, they must have unique names. This means that if both of your assetbundles are templatebundle, they are both incompatible with eachother, and any other mod that did not rename the assetbundle.

**Comment by Callff** [comment]
Ok, good to know. You might also want to update the wiki because under creating a project it says there's no reason to change the assetbundle name.

https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/wiki/Using-the-Unity-Workflow#creating-a-project

**Comment by BunyaPineTree** [comment]
Thank you for letting me know. I thought I changed that, but evidently not.
