### ISSUE TITLE
Visual Studio 20016 Errors & 1522 Warnings

### ISSUE THREAD

**Issue by DipReapyy** [BunyaPineTree/LethalCompany_ModelReplacementAPI#77]
Hi,
I tried to create a mod that adds a new model to the game but when i get to the Visual Studio part, i hit the rebuild button and get 20016 Errors & 1522 Warnings.
I do not know how to code so having a huge amount of issues like this makes it impossible for me to try to figue out what i coud do to fix this by myself. 
From what i chan see the errors are mostly thigs that could not be found or that doesn't exist. 
I dont know if i can paste the whole error list in here so i'll show you a few screenshots.
![image](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/161942766/4d3d94e9-57be-431f-8152-dd57d7b98c23)
![image](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/161942766/20d1439f-4f66-4f69-849d-a980584b8d81)
![image](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/161942766/ee7c4968-7e61-41d7-8ab1-32ce42f9157c)
![image](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/161942766/f9a564f1-3dec-4e53-bd94-6e22d3f0c724)
![image](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/161942766/18d6a7ab-09ba-4720-a1ae-d526692de76b)
![image](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/161942766/4613d374-4507-4fd1-9863-9efbbc582aa7)
I'm completely lost, i don't know if it's my fault (did i forgot to download something ? That coud explain why i have so much things missing).
So if by any chance you have the key to resolve my problems i woud be really grateful !
Have a good day !

**Comment by DipReapyy** [comment]
I figured it out somehow

**Comment by BunyaPineTree** [comment]
Sounds like it's all working then.

**Comment by Retr0sec7** [comment]
@DipReapyy could elaborate on how did you fix this? I getting the closely the same amount of errors, but mines are 20044 erros.

**Comment by DipReapyy** [comment]
Hi @Retr0sec7 it's been a while oi i don't know if i'm gonna explain this clearly but i'll try.
For me it was a folder issue, you need to create a new folder inside your unity project folder and but this inside of it:
- The bin folder
- BodyReplacements.cs
- ModelReplacementAPI.dll
- (YourProjectName).csproj
- Plugin.cs
- And two other files that are realated to you scene prefab
![Capture d'écran 2024-04-10 132042](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/161942766/01e5b2aa-f753-4b64-bb24-be5a58740535)
It should look like this but without the Build and Obj files that wiil be created when you'll hit the rebuild button in Visual Studio.
Now you just have to follow the tutorial where you left it and it should work !
