### ISSUE TITLE
Model Issue

### ISSUE THREAD

**Issue by AndrewHKGithub** [BunyaPineTree/LethalCompany_ModelReplacementAPI#78]
Hi, it's been a minute. Since you helped me learn how to use your tool I've been having a ton of fun importing primarily MMD models into the game, and it's been a really fun and novel way for me to dip my toes into using Unity and Blender, which I've always wanted to but never have proper.
So for a more ambitious project, I found a 3D model from a game that hasn't been rigged at all, and made my first armature-mesh combination with it. It works in Blender and Unity, but when I load it into Lethal the model doesn't appear. I think its because the method I used to construct the model, instead of a single mesh with painted weights, because the 3D model is of a robot with complicated geometry, I opted to make each joint a separate mesh and parented them to bones separately. Do you have any insight on what I can do to get it working in-game?
![Screenshot 2024-03-03 033033](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/33970196/f7cdd650-04a5-4df7-aa32-b042175a7c4a)

**Comment by AndrewHKGithub** [comment]
Oh yeah, and this is the error I get when I try to equip that suit.
![Screenshot 2024-03-03 041142](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/33970196/76e21bcc-7952-447e-b23a-fef8d74198d7)

**Comment by BunyaPineTree** [comment]
That's nice to hear. The best way to build knowledge on things like this really is to have a project that you already want to do. 
Currently the API requires at least one SkinnedMeshRenderer to work, which is probably something that should change, but is that way regardless. 
What you could possibly do is manually weight paint each mesh so that the entire mesh is weighted only to the bone you parented them to.

**Comment by AndrewHKGithub** [comment]
> That's nice to hear. The best way to build knowledge on things like this really is to have a project that you already want to do. Currently the API requires at least one SkinnedMeshRenderer to work, which is probably something that should change, but is that way regardless. What you could possibly do is manually weight paint each mesh so that the entire mesh is weighted only to the bone you parented them to.

Do you know of any specific video tutorial or written guide you recommend on how to go about that? There's so much information out there it's a little overwhelming.

**Comment by BunyaPineTree** [comment]
Unfortunately not. I've built up knowledge on meshes and weight painting purely from my interactions with this mod, but haven't actually done it myself. 

I do know that guides for robotic model weight painting do exist though, which you may be able to go from.

**Comment by AndrewHKGithub** [comment]
> Unfortunately not. I've built up knowledge on meshes and weight painting purely from my interactions with this mod, but haven't actually done it myself.
> 
> I do know that guides for robotic model weight painting do exist though, which you may be able to go from.

I'll check them out! So do you think the issue is that there's no SkinnedMeshRenderer? I'll add that in Blender and see if it fixes the "sequence contains no elements" error.
