### ISSUE TITLE
Problems with the HDLethalCompany

### ISSUE THREAD

**Issue by huluoboya3** [BunyaPineTree/LethalCompany_ModelReplacementAPI#80]
The ModelReplacementAPI causes HDLethalCompany's FOLIAGE TOGGLE to not work
FOLIAGE TOGGLE takes effect when the ModelReplacementAPI is disabled
use MOD：
-ModelReplacementAPI
-HDLethalCompany

**Comment by BunyaPineTree** [comment]
Thanks for the report. 
I have looked into the source code for HDLethalCompany and see the root of the issue and a possible solution. 

At the moment I do not have time to work on this mod, and once I have time again there are more pressing issues I intend on addressing first, so I cannot say when this will be fixed.

**Comment by lotexiu** [comment]
HDLethalCompany is already Deprecated!
