### ISSUE TITLE
GUID conflicts with jiggle physics package?

### ISSUE THREAD

**Issue by Coffely** [BunyaPineTree/LethalCompany_ModelReplacementAPI#81]
Im new to this stuff but when i install both modelreplacement and jigglephysics as packages in the package manager i get this error

![image](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/161380000/823f3941-8b3c-404e-a164-bde998eb5b51)

**Comment by BunyaPineTree** [comment]
JigglePhysics comes bundled with the SDK. Try making a new unity project. In the past people have mistakenly downloaded jigglephysics, and then the SDK provided scripts stopped working as well.

**Comment by Coffely** [comment]
oh that makes sense, i was confused cuz it seems the jiggle rig builder script that is bundled with the sdk is different then showed in the gifs on the jiggle phyics github page
![image](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/161380000/258c76bf-c607-4c27-b355-9398a7e599bb)

**Comment by BunyaPineTree** [comment]
That's because it was modified for use in games. Anyways I'm closing since this appears to be resolved
