### ISSUE TITLE
[Feature Request] Skins without humanoid type rig

### ISSUE THREAD

**Issue by MaverXka** [BunyaPineTree/LethalCompany_ModelReplacementAPI#83]
Add the ability to replace the player’s model with any model, no matter whether it has a rig or not. It’s better to just replace the model with a prefab so there will be more opportunities for customization.

**Comment by BunyaPineTree** [comment]
That was how we originally did it, but so many people had trouble with mapping their generic rig that it was explicitly suggested that we map bones using the humanoid avatar instead. 
This method has been so much more successful in every way than the generic method that there is absolutely no reason to go back. 
People have managed to import generic rigs to begin with in the past simply by having a humanoid skeleton, and then using that skeleton to drive their model's rig, put in some work and you should be able to achieve what ever it is you're interested in.
