### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by diamondbananaman265** [BunyaPineTree/LethalCompany_ModelReplacementAPI#84]
Add a way to update the BodyReplacements.cs with the asset bundles that are in the folder/ in unity, unless there's an easy way to already to do that and I dont know about it.

**Comment by BunyaPineTree** [comment]
Simply put, there is no way to identify what needs to be changed in BodyReplacements.cs that doesn't have the possibility of failure or deletion of the user's work. 

If you can find some way to do that then feel free to submit a PR.
