### ISSUE TITLE
[REQUEST] First-person camera height view from model height 

### ISSUE THREAD

**Issue by akronman1** [BunyaPineTree/LethalCompany_ModelReplacementAPI#86]
I would like to see ability to change the height of camera according to height of model. Some chibi and small models might be too wide or big and not proportional with normal characters

**Comment by Edouard127** [comment]
You can get the player head bone position
Look how I did it here

https://github.com/Edouard127/LethalWarfare2/blob/master/Modules/Patches/PlayerPatch.cs

**Comment by akronman1** [comment]
Im not programmer, I dont know where you get head bone position to write first-personal camera position.

**Comment by BunyaPineTree** [comment]
If you want to change the camera height then researching the source code Edouard127 offered is a great way to go about it, though of course you'll have to familiarize yourself with enough programming to achieve that. 

I plan on keeping ModelReplacementAPI as a cosmetic only API. Changing the location of the camera would likely create advantages or disadvantages for the player, so I won't add direct support for it, but I do encourage that you try it yourself.
