### ISSUE TITLE
Compatibility issue with "ClearFirstPerson"

### ISSUE THREAD

**Issue by dounai2333** [BunyaPineTree/LethalCompany_ModelReplacementAPI#88]
After installed the latest version of ModelReplacementAPI, I have noticed another mod call [ClearFirstPerson](https://thunderstore.io/c/lethal-company/p/Mhz/ClearFirstPerson/) no longer working.
Rollback ModelReplacementAPI to version 2.3.9 fixes the compatibility issue.

**Comment by BunyaPineTree** [comment]
Thanks for the report, I should be able to put out a fix today.
