### ISSUE TITLE
[performance issues] error and cause frame dropping

### ISSUE THREAD

**Issue by CoolLKKPS** [BunyaPineTree/LethalCompany_ModelReplacementAPI#91]
[Error  : Unity Log] IndexOutOfRangeException: Index was outside the bounds of the array.
Stack trace:
ModelReplacement.Patches.LocateHeldObjectsOnModelReplacementPatch.LateUpdatePatch (GrabbableObject& __instance) (at <d0a5718937044f3eb970c90c8db8fde6>:0)
(wrapper dynamic-method) GrabbableObject.DMD<GrabbableObject::LateUpdate>(GrabbableObject)

**Comment by BunyaPineTree** [comment]
Consider adding details. I can't help you with some random console output.

**Comment by CoolLKKPS** [comment]
maybe that's the false issues, will keep tracking if this issues happen again
