### ISSUE TITLE
LOD Model is displayed when used with TooManyEmotes

### ISSUE THREAD

**Issue by DarthLilo** [BunyaPineTree/LethalCompany_ModelReplacementAPI#92]
When using ModelReplacementAPI (you don't need to actually replace any models, just the API) and load TooManyEmotes the LOD player model will be shown during emoting, this doesn't happen before view models were added and I have found no solution other than downgrading it.

Only mods were
- ModelReplacementAPI
- TooManyEmotes
- TooManyEmotesScrap

**Comment by BunyaPineTree** [comment]
Is this true for just the local player or all players?

**Comment by DarthLilo** [comment]
From my testing it only happened with the local player, specifically when their own model is rendering due to the 3rd person camera from TME

**Comment by BunyaPineTree** [comment]
Thanks that's very helpful. I'll see if I can't get out an update today or tomorrow.

**Comment by JDWMGB** [comment]
Similar thing to TooManyEmotes, but when using this with LethalEmotesAPI and any emote mod for it like Tf2Emotes this will happen
![Medal_qz6X9Zqqpq](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/43325046/83cbb4f9-0953-421b-aeab-39e5f42430af)

**Comment by BunyaPineTree** [comment]
Can you confirm that this still happens? I'm not getting it on my end. 

ModelReplacementAPI
TooManyEmotes
![image](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/63533840/4b673d9a-24a7-4930-9762-0f13654cf541)

ModelReplacementAPI
LethalEmotesAPI
![image](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/63533840/6f4eec72-5d53-460b-8f21-cfb25b152dad)

**Comment by JDWMGB** [comment]
From when I last tested it seems to be fixed now

**Comment by BunyaPineTree** [comment]
Thanks. I'll close it as resolved then.
