### ISSUE TITLE
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by CoolLKKPS** [BunyaPineTree/LethalCompany_ModelReplacementAPI#93]
[13:43:15.4771645] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ModelReplacement.Patches.CosmeticPatch.Postfix () (at <828e84791a024ae4a8ff103c631b7786>:IL_0021)
(wrapper dynamic-method) HUDManager.DMD<HUDManager::AddTextMessageClientRpc>(HUDManager,string)
HUDManager.__rpc_handler_1568596901 (Unity.Netcode.NetworkBehaviour target, Unity.Netcode.FastBufferReader reader, Unity.Netcode.__RpcParams rpcParams) (at <09f109276c764f589f47f312aab5547a>:IL_0066)
Unity.Netcode.RpcMessageHelpers.Handle (Unity.Netcode.NetworkContext& context, Unity.Netcode.RpcMetadata& metadata, Unity.Netcode.FastBufferReader& payload, Unity.Netcode.__RpcParams& rpcParams) (at <895801699cfc4b4ab52267f31e2a4998>:IL_004E)
Rethrow as Exception: Unhandled RPC exception!
UnityEngine.Logger:LogException(Exception, Object)
AsyncLoggers.Wrappers.Unity.<>c__DisplayClass4_0:<LogException>b__0() (at ./src/Wrappers/Unity/AsyncLoggerWrapper.cs:36)
AsyncLoggers.Wrappers.Unity.<>c__DisplayClass28_0:<wrapCallback>b__0() (at ./src/Wrappers/Unity/AsyncLoggerWrapper.cs:136)
AsyncLoggers.Wrappers.JobWrapper:LogWorker() (at ./src/Wrappers/JobWrapper.cs:84)
AsyncLoggers.Wrappers.LogJob:Execute() (at ./src/Wrappers/JobWrapper.cs:68)
Unity.Jobs.JobStruct`1:Execute(LogJob&, IntPtr, IntPtr, JobRanges&, Int32)

[13:43:15.4791665] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ModelReplacement.Patches.CosmeticPatch.Postfix () (at <828e84791a024ae4a8ff103c631b7786>:IL_0021)
(wrapper dynamic-method) HUDManager.DMD<HUDManager::AddTextMessageClientRpc>(HUDManager,string)
(wrapper dynamic-method) HUDManager.DMD<HUDManager::AddTextMessageServerRpc>(HUDManager,string)
HostFixes.Plugin+HostFixesServerReceiveRpcs.AddTextMessageServerRpc (System.String chatMessage, Unity.Netcode.ServerRpcParams serverRpcParams) (at ./Plugin.cs:525)
(wrapper dynamic-method) HUDManager.DMD<HUDManager::__rpc_handler_2787681914>(Unity.Netcode.NetworkBehaviour,Unity.Netcode.FastBufferReader,Unity.Netcode.__RpcParams)
Unity.Netcode.RpcMessageHelpers.Handle (Unity.Netcode.NetworkContext& context, Unity.Netcode.RpcMetadata& metadata, Unity.Netcode.FastBufferReader& payload, Unity.Netcode.__RpcParams& rpcParams) (at <895801699cfc4b4ab52267f31e2a4998>:IL_004E)
Rethrow as Exception: Unhandled RPC exception!
UnityEngine.Logger:LogException(Exception, Object)
AsyncLoggers.Wrappers.Unity.<>c__DisplayClass4_0:<LogException>b__0() (at ./src/Wrappers/Unity/AsyncLoggerWrapper.cs:36)
AsyncLoggers.Wrappers.Unity.<>c__DisplayClass28_0:<wrapCallback>b__0() (at ./src/Wrappers/Unity/AsyncLoggerWrapper.cs:136)
AsyncLoggers.Wrappers.JobWrapper:LogWorker() (at ./src/Wrappers/JobWrapper.cs:84)
AsyncLoggers.Wrappers.LogJob:Execute() (at ./src/Wrappers/JobWrapper.cs:68)
Unity.Jobs.JobStruct`1:Execute(LogJob&, IntPtr, IntPtr, JobRanges&, Int32)

**Comment by CoolLKKPS** [comment]
that cause u cannot see other player cosmetic

**Comment by BunyaPineTree** [comment]
Thanks. I've had similar reports on this error and have removed that patch for the time being. Let me know if it still persists.

**Comment by CoolLKKPS** [comment]
works great now :), yea i think maybe no longer need that patch, maybe, will close this ticket anyway
