### ISSUE TITLE
Model didn't correct destroyed upon disconnect while having "MoreCompany" installed

### ISSUE THREAD

**Issue by dounai2333** [BunyaPineTree/LethalCompany_ModelReplacementAPI#95]
This issue only happens if you have "MoreCompany" installed.
When a player disconnect from current game when he is alive, the playermodel will not get correct destroyed, and will remain visible until the player slot is being used again.

**Comment by BunyaPineTree** [comment]
There's not much I can do about this. It's a bug that the MoreCompany developer needs to fix.
