### ISSUE TITLE
Modded Suits not showing up

### ISSUE THREAD

**Issue by CYCzen** [BunyaPineTree/LethalCompany_ModelReplacementAPI#96]
Hello, my customs suits were working a while back but it stopped working & no suits are showing up in game.
Is this mod in conflict with any of my other mods?

![Untitled](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/89285878/6b9064de-3bd4-4eb7-a599-a730574929a8)

![Screenshot 2024-04-19 175218](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/89285878/51d96c27-6f01-4f93-a684-9b2828a53bd6)
![Screenshot 2024-04-20 111544](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/89285878/32d453c7-005c-4ff4-8001-5bb3ea59fdd7)

**Comment by BunyaPineTree** [comment]
I would love to know what causes the rack being empty myself, as it's a common issue I experience, but doesn't have anything to do with the API. Often times I can fix this by quitting to main menu and restarting that save. 

Regarding the exceptions in console, do you have Too Many Emotes installed? That might indicate a new bug that is unrelated to the modded suits being missing.

**Comment by CYCzen** [comment]
> I would love to know what causes the rack being empty myself, as it's a common issue I experience, but doesn't have anything to do with the API. Often times I can fix this by quitting to main menu and restarting that save.
> 
> Regarding the exceptions in console, do you have Too Many Emotes installed? That might indicate a new bug that is unrelated to the modded suits being missing.

I've traced the issue back to the "Too many emote" mod, disabling it makes the suits visible again

**Comment by CYCzen** [comment]
Good news, it's working again
![image](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/89285878/ae33dfc5-9569-4428-8881-39dfe6d58fbc)

**Comment by BunyaPineTree** [comment]
I am skeptical that this is related to the issue. I don't install TooManyEmotes when doing my testing, but I get this issue frequently. 

Regardless, I'll close the issue, as it seems to be resolved, and is unrelated to my API to begin with.
