### ISSUE TITLE
the character models are displayed crookedly

### ISSUE THREAD

**Issue by Ilja24rus** [BunyaPineTree/LethalCompany_ModelReplacementAPI#97]
![image](https://github.com/BunyaPineTree/LethalCompany_ModelReplacementAPI/assets/42020630/6e17a85e-5766-447d-b413-1ff7f9ed4ba5)

**Comment by BunyaPineTree** [comment]
Could you please explain what you are showing me here?

**Comment by Ilja24rus** [comment]
first-person view

**Comment by BunyaPineTree** [comment]
I don't know what might cause this issue, and it is impossible to determine with no information. If your problem persists, and you can determine anything that might cause it (i.e. errors in console, or simply sending the problematic mod), then feel free to reopen the issue, or post a new one.
