### ISSUE TITLE
Model replacing default and orange suit unintentionally

### ISSUE THREAD

**Issue by jrozay** [BunyaPineTree/LethalCompany_ModelReplacementAPI#98]
When creating a model ive noticed the three ive made so far has unintentionally replaced the default, orange, and the png ive coded it to replace. Is there anyway to avoid it replacing the default suits? or am i just missing a step completely...

**Comment by BunyaPineTree** [comment]
If you have added your own suit, you need to remove the config options, or change their default value to your png.

**Comment by BunyaPineTree** [comment]
Seeing as it has been two weeks. I'm going to assume that this helped your problem. If that isn't the case, this issue can be reopened.
