### ISSUE TITLE
Model Buggy with Weapons/Tools being held. 

### ISSUE THREAD

**Issue by AvnoArts** [BunyaPineTree/LethalCompany_ModelReplacementAPI#99]
like.. shotgun? all-over, shovel? also, in a weird place. flashlight? inside the hand. just to point out..

**Comment by AvnoArts** [comment]
for the ArkKnights Lappland one i for one. and the Blue Archive models i'm pretty sure

**Comment by BunyaPineTree** [comment]
That's a question for the person who made the mod. From an API standpoint, it's impossible to determine the correct location to place items.
